### ISSUE TITLE
Comply with E731: do not assign a lambda expression, use a def

### ISSUE THREAD

**Issue by amiv1** [kofrasa/migrate#5]
[migrate.py:206:1](https://github.com/kofrasa/migrate/blob/0.3.7/migrate.py#L205): `exec_sqlite3 = lambda a, b, c, d: exec_mysql(a, b, None, d)`
According to PEP8 this is an anti pattern.

See [Programming Recommendations](http://legacy.python.org/dev/peps/pep-0008/#programming-recommendations):

> Always use a def statement instead of an assignment statement that binds a lambda expression directly to an identifier.
> 
> Yes:
> 
> `def f(x): return 2*x`
> 
> No:
> 
> `f = lambda x: 2*x`
> 
> The first form means that the name of the resulting function object is specifically 'f' instead of the generic '<lambda>'. This is more useful for tracebacks and string representations in general. The use of the assignment statement eliminates the sole benefit a lambda expression can offer over an explicit def statement (i.e. that it can be embedded inside a larger expression)

Also, is it even being used? I couldn't find any reference to `exec_sqlite3` in the code at all.

**Comment by kofrasa** [comment]
The `exec_<engine>` functions are called dynamically for the appropriate database target. Useful note about the tracebacks.

**Comment by kofrasa** [comment]
Addressed in release 0.3.8. Thank you
