### ISSUE TITLE
Comply with E402: module level import not at top of file

### ISSUE THREAD

**Issue by amiv1** [kofrasa/migrate#6]
[migrate.py:15-23](https://github.com/kofrasa/migrate/blob/0.3.7/migrate.py#L15)
According to PEP8, all module level imports should be on top of the file.

See [Code lay-out](https://www.python.org/dev/peps/pep-0008/#imports):

> Imports are always put at the top of the file, just after any module comments and docstrings, and before module globals and constants.
> 
> Imports should be grouped in the following order:
> 
> ```
> standard library imports
> related third party imports
> local application/library specific imports
> ```
> 
> You should put a blank line between each group of imports.
> 
> Put any relevant `__all__` specification after the imports.

**Comment by kofrasa** [comment]
I agree. Standards or lack thereof will be the death of us :-)
